# Generated by Django 4.0.2 on 2022-03-08 07:55

import uuid

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=15)),
                (
                    "weight",
                    models.IntegerField(
                        default=0, help_text="Calculated ROI with data from events."
                    ),
                ),
                (
                    "grid_position",
                    models.IntegerField(
                        default=0, help_text="Its order on the output grid."
                    ),
                ),
                (
                    "url",
                    models.URLField(help_text="URI where the image is located at."),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "views",
                    models.IntegerField(
                        default=0, help_text="Time the image has been seen."
                    ),
                ),
                (
                    "clicks",
                    models.IntegerField(
                        default=0, help_text="Time the image has been clicked."
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="gallery.image",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
