# Generated by Django 4.0.2 on 2022-03-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0002_alter_image_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Calculated ROI with data from events.",
                max_digits=5,
            ),
        ),
    ]
